import { BadgeCheck, BriefcaseBusiness, Building2, FileSignature, Gavel, Handshake, Landmark, Scale, Shield, Users } from "lucide-react";
export const siteUrl = "https://legarischambers.com";
export const contact = { addressLines: ["7-1-28/1/A/6", "Park Avenue Colony", "Shyam Karan Road", "Ameerpet", "Hyderabad, Telangana - 500016"], phone: "9492010110", email: "info@legarischambers.com", hours: "Monday to Saturday, 10:00 AM - 6:00 PM" };
export const firmSchema = { "@context": "https://schema.org", "@type": "LegalService", name: "Legaris Chambers", url: siteUrl, telephone: contact.phone, email: contact.email, address: { "@type": "PostalAddress", streetAddress: "7-1-28/1/A/6, Park Avenue Colony, Shyam Karan Road, Ameerpet", addressLocality: "Hyderabad", addressRegion: "Telangana", postalCode: "500016", addressCountry: "IN" } };
export const navLinks = [{href:"/",label:"Home"},{href:"/about",label:"About"},{href:"/practice-areas",label:"Practice Areas"},{href:"/our-people",label:"Our People"},{href:"/contact",label:"Contact"}];
export const practiceAreas = [
{ slug:"civil-litigation", title:"Civil Litigation", short:"Representation in civil disputes, suits, injunctions, and related proceedings.", icon:Landmark, accent:"#D4AF37", theme:"Courtroom", image:"https://images.unsplash.com/photo-1589994965851-a8f479c573a9?auto=format&fit=crop&w=1800&q=82", pattern:"patterned", services:["Civil suits and injunctions","Recovery proceedings","Property-related disputes","Appeals and revisions"], approach:"We assess pleadings, documentary strength, interim relief options, and procedural strategy before recommending the path forward." },
{ slug:"criminal-litigation", title:"Criminal Litigation", short:"Professional assistance in criminal complaints, bail matters, trial support, and defense strategy.", icon:Shield, accent:"#C9A96E", theme:"Justice", image:"https://images.unsplash.com/photo-1593115057322-e94b77572f20?auto=format&fit=crop&w=1800&q=82", pattern:"bg-[radial-gradient(circle_at_top_left,rgba(201,169,110,0.2),transparent_32%)]", services:["Bail and anticipatory bail","Complaint drafting","Trial preparation","Quashing and appellate remedies"], approach:"Each matter is handled with careful review of facts, evidence, timelines, statutory provisions, and court procedure." },
{ slug:"property-real-estate", title:"Property & Real Estate", short:"Legal support for property transactions, title review, disputes, and documentation.", icon:Building2, accent:"#B8C7D9", theme:"Architecture", image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=82", pattern:"bg-[linear-gradient(135deg,rgba(184,199,217,0.14),transparent_42%)]", services:["Title due diligence","Sale and lease documentation","Partition and possession disputes","Development agreements"], approach:"We focus on documentary clarity, chain of title, encumbrances, regulatory issues, and enforceable transaction terms." },
{ slug:"corporate-advisory", title:"Corporate Advisory", short:"Advisory support for businesses, founders, institutions, and commercial decision-making.", icon:BriefcaseBusiness, accent:"#A8B5A0", theme:"Boardroom", image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1800&q=82", pattern:"bg-[linear-gradient(90deg,rgba(168,181,160,0.16),transparent_48%)]", services:["Business structuring","Commercial advisory","Regulatory coordination","Risk review"], approach:"Our advisory work is designed to translate legal risk into clear decisions, practical documents, and workable next steps." },
{ slug:"contracts-documentation", title:"Contracts & Documentation", short:"Drafting and review of commercial, personal, property, and institutional documents.", icon:FileSignature, accent:"#D8BE7F", theme:"Contract Drafting", image:"https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1800&q=82", pattern:"bg-[radial-gradient(circle_at_center,rgba(216,190,127,0.16),transparent_36%)]", services:["Agreements and contracts","Notices and replies","Affidavits and declarations","Policy and compliance documents"], approach:"Documents are drafted for enforceability, clarity, factual accuracy, and alignment with the intended legal and commercial outcome." },
{ slug:"arbitration-dispute-resolution", title:"Arbitration & Dispute Resolution", short:"Structured dispute strategy for arbitration, negotiation, mediation, and settlement.", icon:Handshake, accent:"#C8B6A6", theme:"Negotiation", image:"https://images.unsplash.com/photo-1573164574511-73c773193279?auto=format&fit=crop&w=1800&q=82", pattern:"bg-[linear-gradient(45deg,rgba(200,182,166,0.16),transparent_44%)]", services:["Arbitration notices","Statement of claim and defense","Settlement negotiations","Mediation support"], approach:"We identify leverage, contractual remedies, evidentiary needs, and resolution options before proceedings escalate." },
{ slug:"family-matrimonial", title:"Family & Matrimonial Matters", short:"Sensitive legal assistance for family disputes, matrimonial issues, and related proceedings.", icon:Users, accent:"#D7B9A8", theme:"Professional Consultation", image:"https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1800&q=82", pattern:"bg-[radial-gradient(circle_at_top_right,rgba(215,185,168,0.18),transparent_38%)]", services:["Matrimonial proceedings","Maintenance and custody issues","Family settlements","Domestic violence matters"], approach:"We combine procedural care with discretion, prioritizing lawful remedies, privacy, and measured communication." },
{ slug:"consumer-matters", title:"Consumer Matters", short:"Assistance with consumer complaints, service deficiencies, product disputes, and forum proceedings.", icon:BadgeCheck, accent:"#E0C46C", theme:"Consumer Rights", image:"https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1800&q=82", pattern:"bg-[linear-gradient(160deg,rgba(224,196,108,0.16),transparent_45%)]", services:["Consumer complaints","Deficiency in service matters","Insurance and billing disputes","Forum representation"], approach:"We evaluate purchase records, correspondence, statutory remedies, and forum jurisdiction to prepare a focused complaint strategy." }
];
export const values = [{title:"Integrity",text:"Clear guidance anchored in professional responsibility.",icon:Scale},{title:"Professional Excellence",text:"Careful preparation, disciplined drafting, and precise advocacy.",icon:Gavel},{title:"Confidentiality",text:"Discreet handling of sensitive personal and commercial matters.",icon:Shield},{title:"Strategic Counsel",text:"Practical legal direction shaped around the matter at hand.",icon:Scale}];
